version: '3.1'
services:
  mediawiki:
    image: mediawiki:latest
    container_name: mediawiki
    ports:
      - "8087:80"
    environment:
      - MEDIAWIKI_SITE_NAME=MyWiki
      - MEDIAWIKI_ADMIN_USER=admin
      - MEDIAWIKI_ADMIN_PASSWORD=password
    volumes:
      - mediawiki_data:/var/www/html/images
  db:
    image: mariadb:10.6
    container_name: mediawiki_db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mediawiki
      - MYSQL_USER=wikiuser
      - MYSQL_PASSWORD=wikisecret
    volumes:
      - mariadb_data:/var/lib/mysql
volumes:
  mediawiki_data:
  mariadb_data:
