version: '3.8'

services:
  web:
    image: php:7.4-apache
    container_name: paginaweb-web-1
    build:
      context: .
    ports:
      - "8081:80"
    volumes:
      - ./app:/var/www/html
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: paginaweb-db-1
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: portfolio
      MYSQL_USER: portfolio_user
      MYSQL_PASSWORD: portfolio_password
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql

volumes:
  db_data:
